version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    
  back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: back
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    restart: unless-stopped